export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const POST_LOADING = 'POST_LOADING'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POSTS = 'UPDATE_POSTS'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const DELETE_POST = 'DELETE_POST'
export const CLEAR_POSTS = 'CLEAR_POSTS'
